### PR TITLE
fix(Canvas): Canvas directive to component implementation

### LINKED ISSUE #636: Canvas is a directive, consider rewriting it as a component
Consider rewriting the canvas directive as a component.

From slack:
>dana [6:27 AM] 
>Canvas is actually a directive internally - it has a link function and binds to several document listeners

### PR DESCRIPTION
**Pull request by amarie401**
## Description
Conversion of the Canvas directive to a component. This fixes #636 

[Rawgit](https://rawgit.com/amarie401/angular-patternfly/canvas-to-component-dist/dist/docs/index.html#/api/patternfly.canvas.component:pfCanvas)

### CODE REVIEW

**Comment by dtaylor113** [comment]
Other than the keystroke issue, LGTM :+1: !

**Comment by amarie401** [comment]
Thanks @dtaylor113 going to look into that issue now

File: src/canvas-view/canvas/canvas-component.js [hunk 1]
```diff
@@ -0,0 +1,411 @@
...
+        ctrl.zoomLevel = function () {
+          return ctrl.chart.zoom.getLevel();
+        };
+
+        ctrl.$onInit = function () {
+          var deleteKeyCode = 46;
+          var ctrlKeyCode = 17;
+          var ctrlDown = false;
+          var aKeyCode = 65;
+          var dKeyCode = 68;
```
Comment (jeff-phillips-18) [inline src/canvas-view/canvas/canvas-component.js]: this is not used

File: src/canvas-view/canvas/canvas-component.js [hunk 2]
```diff
@@ -0,0 +1,411 @@
...
+          if (ctrl.chart.inConnectingMode && node !== ctrl.connectingModeSourceNode) {
+            ctrl.chart.createNewConnection(ctrl.connectingModeOutputConnector, ctrl.mouseOverConnector);
+            ctrl.stopConnectingMode();
+          }
+        };
+
+        //
+        // zoom.
+        //
+        $scope.$on('zoomIn', function (evt, args) {
```
Comment (jeff-phillips-18) [inline src/canvas-view/canvas/canvas-component.js]: arguments are not used

File: src/canvas-view/canvas/canvas-component.js [hunk 3]
```diff
@@ -0,0 +1,411 @@
...
+          ctrl.chart.zoom.in();
+        });
+
+        $scope.$on('zoomOut', function (evt, args) {
```
Comment (jeff-phillips-18) [inline src/canvas-view/canvas/canvas-component.js]: arguments are not used

**Comment by amarie401** [comment]
@dtaylor113 keys should be working now. There was an issue where the mac keyboards use the backspace keycode for "delete" so had to account for both.

**Comment by dtaylor113** [comment]
Hi @amarie401. think you have some debugging code in there :-)
```
/home/travis/build/patternfly/angular-patternfly/src/canvas-view/canvas/canvas-component.js
  392:13  error  Unexpected console statement  no-console
```

File: src/canvas-view/canvas-editor/toolbox-items.component.js [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+        startDragCallback: '=',
+        clickCallback: '=',
+        searchText: '='
+      },
+      controller: function toolboxItemsController () {
+        var ctrl = this;
+
+        ctrl.clickCallbackfmDir = function (item) {
+          if (!item.disableInToolbox) {
+            ctrl.clickCallback(item);
```
Comment (cdcabrera) [inline src/canvas-view/canvas-editor/toolbox-items.component.js]: This may have been in the existing directive, but if we're going for consistency...

we do checks for a function within the ```node-toolbar-component.js``` should we be doing that here too?
Similar too...
```js
if (angular.isFunction(ctrl.clickCallback)) {...
```

File: src/canvas-view/canvas-editor/toolbox-items.component.js [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+          }
+        };
+
+        ctrl.startDragCallbackfmDir = function (event, ui, item) {
+          ctrl.startDragCallback(event, ui, item);
```
Comment (cdcabrera) [inline src/canvas-view/canvas-editor/toolbox-items.component.js]: Same call out on function check...
```js
if (angular.isFunction(ctrl.startDragCallback)) {...
```

File: src/canvas-view/canvas-editor/toolbox-items.component.js [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+
+  angular.module('patternfly.canvas')
+    .component('toolboxItems', {
+      templateUrl: 'canvas-view/canvas-editor/toolbox-items.html',
+      bindings: {
+        items: '=',
+        startDragCallback: '=',
+        clickCallback: '=',
+        searchText: '='
+      },
```
Comment (cdcabrera) [inline src/canvas-view/canvas-editor/toolbox-items.component.js]: One-way binds for the ```callbacks``` using ```<``` do they work? Or do we need some form of the function/callback passed back out?

File: src/canvas-view/canvas/node-toolbar.component.js [hunk 7]
```diff
@@ -0,0 +1,32 @@
...
+
+  angular.module('patternfly.canvas')
+    .component('nodeToolbar', {
+      templateUrl: 'canvas-view/canvas/node-toolbar.html',
+      bindings: {
+        node: '=',
+        nodeActions: '=',
+        nodeClickHandler: '=',
+        nodeCloseHandler: '='
+      },
```
Comment (cdcabrera) [inline src/canvas-view/canvas/node-toolbar.component.js]: Same comment regarding using one-way binds instead of two-way on the ```-Handlers``` using ```<```, do we need the handlers passed back out?

File: src/canvas-view/canvas-editor/toolbox-items.component.js (hunk 6 above)
Comment (amarie401) [reply src/canvas-view/canvas-editor/toolbox-items.component.js]: The one-way binds seem to work in this case.

File: src/canvas-view/canvas-editor/toolbox-items.component.js (hunk 4 above)
Comment (amarie401) [reply src/canvas-view/canvas-editor/toolbox-items.component.js]: Can do. Makes sense for consistency purposes.

File: src/canvas-view/canvas/node-toolbar.component.js (hunk 7 above)
Comment (amarie401) [reply src/canvas-view/canvas/node-toolbar.component.js]: From my knowledge, I don't believe the handlers need to be passed back out. Can change these to one-way binds as well.

File: src/canvas-view/canvas-editor/toolbox-items.component.js (hunk 5 above)
Comment (amarie401) [reply src/canvas-view/canvas-editor/toolbox-items.component.js]: Agree..

File: src/canvas-view/canvas/node-toolbar.component.js [hunk 8]
```diff
@@ -0,0 +1,32 @@
...
+  'use strict';
+
+  angular.module('patternfly.canvas')
+    .component('nodeToolbar', {
+      templateUrl: 'canvas-view/canvas/node-toolbar.html',
+      bindings: {
+        node: '=',
+        nodeActions: '=',
+        nodeClickHandler: '=',
+        nodeCloseHandler: '='
```
Comment (jeff-phillips-18) [inline src/canvas-view/canvas/node-toolbar.component.js]: We should add comments here (since there is no doc for this) as to what the callback arguments should be.

File: src/canvas-view/canvas/node-toolbar.component.js [hunk 9]
```diff
@@ -0,0 +1,32 @@
...
+      },
+      controller: function NodeToolbarController () {
+        var ctrl = this;
+        ctrl.selectedAction = "none";
+
+        ctrl.actionIconClicked = function (action) {
+          ctrl.selectedAction = action;
+          if (angular.isFunction(ctrl.nodeClickHandler)) {
+            ctrl.nodeClickHandler({'action': action, 'node': ctrl.node});
```
Comment (jeff-phillips-18) [inline src/canvas-view/canvas/node-toolbar.component.js]: Might be better to pass 2 arguments rather than an object.

File: src/canvas-view/canvas/canvas-component.js [hunk 10]
```diff
@@ -0,0 +1,411 @@
...
+          var backspaceKeyCode = 8;
+          var deleteKeyCode = 46;
+          var ctrlKeyCode = 17;
+          var ctrlDown = false;
+          var aKeyCode = 65;
+          var escKeyCode = 27;
+
+          $document.find('body').keydown(function (evt) {
+            if (evt.keyCode === ctrlKeyCode) {
+              ctrlDown = true;
```
Comment (jeff-phillips-18) [inline src/canvas-view/canvas/canvas-component.js]: You can check evt.ctrlKey to determine if ctrl is pressed rather than keeping state.

File: src/canvas-view/canvas/canvas-component.js [hunk 11]
```diff
@@ -0,0 +1,411 @@
...
+              ctrl.deselectAll();
+              $scope.$digest();
+            }
+
+            if (evt.keyCode === ctrlKeyCode) {
+              ctrlDown = false;
+              evt.stopPropagation();
+              evt.preventDefault();
+            }
+          });
```
Comment (jeff-phillips-18) [inline src/canvas-view/canvas/canvas-component.js]: Why keyup sometimes and keydown others? I would think we could check only on keydown for all of these.

File: src/canvas-view/canvas-editor/toolbox-items.component.js (hunk 6 above)
Comment (cdcabrera) [reply src/canvas-view/canvas-editor/toolbox-items.component.js]: @jeff-phillips-18 @dtaylor113 since the syntax on the consumption end should be the same is there a contrast opinion to updating the syntax?

Comment (jeff-phillips-18) [reply src/canvas-view/canvas-editor/toolbox-items.component.js]: works for me.

File: src/canvas-view/canvas/node-toolbar.component.js (hunk 9 above)
Comment (amarie401) [reply src/canvas-view/canvas/node-toolbar.component.js]: I agree

File: src/canvas-view/canvas-editor/toolbox-items.component.js (hunk 4 above)
Comment (amarie401) [reply src/canvas-view/canvas-editor/toolbox-items.component.js]: After looking into it, seems like ```ctrl.clickCallback ``` isn't a function so would be unable to check for a function in this instance

File: src/canvas-view/canvas-editor/toolbox-items.component.js (hunk 5 above)
Comment (amarie401) [reply src/canvas-view/canvas-editor/toolbox-items.component.js]: Same as above ```ctrl.startDragCallback``` isn't a function either. Just being used for binding and to pass the arguments into from the it's parent function.

File: src/canvas-view/canvas-editor/toolbox-items.component.js (hunk 4 above)
Comment (jeff-phillips-18) [reply src/canvas-view/canvas-editor/toolbox-items.component.js]: If it isn't a function, how is it being called?

Comment (amarie401) [reply src/canvas-view/canvas-editor/toolbox-items.component.js]: Or maybe I'm misunderstanding

**Comment by amarie401** [comment]
@cdcabrera @jeff-phillips-18 made some requested changes. Still working on fixing the eventText issue.

File: src/canvas-view/canvas-editor/toolbox-items.component.js [hunk 12]
```diff
@@ -0,0 +1,31 @@
...
+        clickCallback: '<',
+        searchText: '='
+      },
+      controller: function toolboxItemsController () {
+        var ctrl = this;
+
+        ctrl.clickCallbackfmDir = function (item) {
+          if (angular.isFunction(ctrl.clickCallback)) {
+            if (!item.disableInToolbox) {
+              ctrl.clickCallback(item);
```
Comment (jeff-phillips-18) [inline src/canvas-view/canvas-editor/toolbox-items.component.js]: I would && these together for readability.

File: src/canvas-view/canvas-editor/toolbox-items.component.js [hunk 13]
```diff
@@ -0,0 +1,31 @@
...
+      bindings: {
+        items: '=',
+        startDragCallback: '<',
+        clickCallback: '<',
+        searchText: '='
+      },
+      controller: function toolboxItemsController () {
+        var ctrl = this;
+
+        ctrl.clickCallbackfmDir = function (item) {
```
Comment (jeff-phillips-18) [inline src/canvas-view/canvas-editor/toolbox-items.component.js]: This is an odd name for the function, what does the 'fm' mean?

Comment (amarie401) [reply src/canvas-view/canvas-editor/toolbox-items.component.js]: I have no idea. They were already named these lol

Comment (dtaylor113) [reply src/canvas-view/canvas-editor/toolbox-items.component.js]: That stood for 'from directive'.  I think at some point just 'clickCallback' wasn't descriptive enough.

File: src/canvas-view/canvas/canvas-component.js [hunk 14]
```diff
@@ -0,0 +1,406 @@
...
+    // Component that generates the rendered chart from the data model.
+    //
+    .component('pfCanvas', {
+      templateUrl: "canvas-view/canvas/canvas.html",
+      bindings: {
+        chartDataModel: "=",
+        chartViewModel: "=?",
+        readOnly: "=?",
+        hideConnectors: "=?"
+      },
```
Comment (cdcabrera) [inline src/canvas-view/canvas/canvas-component.js]: We seem to flip back and forth between double quotes and single without a clear reason? Do you have a preference, or you up for making them consistent? If so encourage you to go back through and check them.

File: src/canvas-view/canvas/canvas-component.js [hunk 15]
```diff
@@ -0,0 +1,406 @@
...
+              ctrl.deselectAll();
+              $scope.$digest();
+            }
+
+            if (evt.keyCode === ctrlKeyCode) {
+              evt.ctrlKey = false;
+              evt.stopPropagation();
+              evt.preventDefault();
+            }
+          });
```
Comment (cdcabrera) [inline src/canvas-view/canvas/canvas-component.js]: Just a note you don't need to change it. 

This could have also been flipped to a switch. However it probably wouldn't save us much...

```js
switch(evt.keyCode) {
  case deleteKeyCode:
  case backspaceKeyCode:
    ctrl.deleteSelected();
    $scope.$digest();
    break;

  case escKeyCode:
    ctrl.deselectAll();
    $scope.$digest();
    break;

  case ctrlKeyCode:
    evt.ctrlKey = false;
    evt.stopPropagation();
    evt.preventDefault();
    break;
}
```

File: src/canvas-view/canvas/node-toolbar.component.js [hunk 16]
```diff
@@ -0,0 +1,34 @@
+(function () {
+  'use strict';
+
+  angular.module('patternfly.canvas')
+    .component('nodeToolbar', {
+      templateUrl: 'canvas-view/canvas/node-toolbar.html',
+      bindings: {
+        node: '=',
+        nodeActions: '=',
+        nodeClickHandler: '<', // @callback args - (action {string}, node {Object})
```
Comment (cdcabrera) [inline src/canvas-view/canvas/node-toolbar.component.js]: We sure about calling them arguments... what about parameters? 

Also it may be a good idea to be consistent and apply similar comments to other callbacks that pass parameters back.

File: src/canvas-view/examples/canvas.js [hunk 17]
```diff
@@ -163,7 +169,7 @@
                     "fontFamily": "PatternFlyIcons-webfont",
                     "fontContent": "\ue621"
                   }
-                ],
+                ]
```
Comment (cdcabrera) [inline src/canvas-view/examples/canvas.js]: Good catch on going through the examples and cleaning up! Thank you!

File: src/canvas-view/canvas/canvas-component.js [hunk 18]
```diff
@@ -0,0 +1,406 @@
...
+          var svgElem =  $element.get(0).children[0];
+          var matrix = svgElem.getScreenCTM();
+          var point = svgElem.createSVGPoint();
+          point.x = (x - evt.view.pageXOffset) / ctrl.zoomLevel();
+          point.y = (y - evt.view.pageYOffset) / ctrl.zoomLevel();
+
+          return point.matrixTransform(matrix.inverse());
+        };
+
+        ctrl.hideConnectors = ctrl.hideConnectors ? ctrl.hideConnectors : false;
```
Comment (cdcabrera) [inline src/canvas-view/canvas/canvas-component.js]: You'll have to check it to confirm, but this might be a good spot for some simplification... 
```js
ctrl.hideConnectors = ctrl.hideConnectors || false;
```

File: src/canvas-view/canvas/canvas-component.js (hunk 14 above)
Comment (amarie401) [reply src/canvas-view/canvas/canvas-component.js]: I'm fine with double quotes. I can go back and make them consistent.

File: src/canvas-view/canvas/canvas-component.js (hunk 18 above)
Comment (amarie401) [reply src/canvas-view/canvas/canvas-component.js]: I agree

File: src/canvas-view/canvas/canvas-component.js (hunk 15 above)
Comment (amarie401) [reply src/canvas-view/canvas/canvas-component.js]: I'm fine with changing it to a switch. Looks nice and clean.

File: src/canvas-view/canvas/node-toolbar.component.js (hunk 16 above)
Comment (amarie401) [reply src/canvas-view/canvas/node-toolbar.component.js]: I thought args/params were pretty much the same thing? I actually documented the nodeClickHandler in ng-docs so might not need this comment here.

File: src/canvas-view/canvas/canvas-component.js (hunk 18 above)
Comment (jeff-phillips-18) [reply src/canvas-view/canvas/canvas-component.js]: If the idea is that any value makes this true, then I would use:
```js
ctrl.hideConnectors = !!ctrl.hideConnectors;
```

File: src/canvas-view/canvas/canvas-component.js [hunk 19]
```diff
@@ -0,0 +1,406 @@
...
+        };
+
+        ctrl.zoomLevel = function () {
+          return ctrl.chart.zoom.getLevel();
+        };
+
+        ctrl.$onInit = function () {
+          var backspaceKeyCode = 8;
+          var deleteKeyCode = 46;
+          var ctrlKeyCode = 17;
```
Comment (jeff-phillips-18) [inline src/canvas-view/canvas/canvas-component.js]: This is not needed.

File: src/canvas-view/canvas/canvas-component.js [hunk 20]
```diff
@@ -0,0 +1,406 @@
...
+              ctrl.deleteSelected();
+              $scope.$digest();
+            }
+
+            if (evt.keyCode === escKeyCode) {
+              ctrl.deselectAll();
+              $scope.$digest();
+            }
+
+            if (evt.keyCode === ctrlKeyCode) {
```
Comment (dtaylor113) [inline src/canvas-view/canvas/canvas-component.js]: You should replace this with `evt.ctrlKey === true` like in the Ctrl-A usage.  Then you can get rid of the `ctrlkeyCode` variable like @jeff-phillips-18  suggests.  -thanks!

Comment (amarie401) [reply src/canvas-view/canvas/canvas-component.js]: Will do! Thanks :)

File: src/canvas-view/canvas/canvas-component.js [hunk 21]
```diff
@@ -0,0 +1,406 @@
...
+          var ctrlKeyCode = 17;
+          var aKeyCode = 65;
+          var escKeyCode = 27;
+
+          $document.find('body').keydown(function (evt) {
+            if (evt.ctrlKey === true) {
+              evt.stopPropagation();
+              evt.preventDefault();
+            }
+
```
Comment (dtaylor113) [inline src/canvas-view/canvas/canvas-component.js]: You can get rid of the `if (evt.ctrlKey === true)...stopPropagation` statement since you are no longer keeping track of ctrl key state.

File: src/canvas-view/canvas/canvas-component.js (hunk 18 above)
Comment (amarie401) [reply src/canvas-view/canvas/canvas-component.js]: It appears that it’s already considered a boolean, I could cast it but I think the syntax is a bit confusing

File: src/canvas-view/canvas/node-toolbar.component.js (hunk 16 above)
Comment (amarie401) [reply src/canvas-view/canvas/node-toolbar.component.js]: reworded the ng-docs to encompass the concept of both arguments and parameters for the nodeClickHandler in  the ```canvas.js``` example. Do we still need the comment?

File: src/canvas-view/canvas/canvas-component.js [hunk 22]
```diff
@@ -0,0 +1,393 @@
...
+    //
+    // Component that generates the rendered chart from the data model.
+    //
+    .component('pfCanvas', {
+      templateUrl: 'canvas-view/canvas/canvas.html',
+      bindings: {
+        chartDataModel:'=',
+        chartViewModel: '=?',
+        readOnly: '=?',
```
Comment (cdcabrera) [inline src/canvas-view/canvas/canvas-component.js]: This is non-breaking, but we use a one way bind on the other readOnly binding would that work here too?

File: src/canvas-view/canvas/canvas-component.js [hunk 23]
```diff
@@ -0,0 +1,393 @@
...
+
+        ctrl.$onInit = function () {
+          var backspaceKeyCode = 8;
+          var deleteKeyCode = 46;
+          var aKeyCode = 65;
+          var escKeyCode = 27;
+
+          $document.find('body').keydown(function (evt) {
+
+            if (evt.keyCode === aKeyCode) {
```
Comment (dtaylor113) [inline src/canvas-view/canvas/canvas-component.js]: Hi, you need `evt.ctrlKey === true` here in order to do Ctrl-A, at the moment just hitting 'a' alone will select all.

File: src/canvas-view/canvas/canvas-component.js (hunk 22 above)
Comment (amarie401) [reply src/canvas-view/canvas/canvas-component.js]: Yes it does work here, will change for consistency.

File: src/canvas-view/canvas/canvas-component.js (hunk 23 above)
Comment (amarie401) [reply src/canvas-view/canvas/canvas-component.js]: ahh yes good catch!

**Comment by amarie401** [comment]
We don't seem to unit test this set of components, is that something we could aim for?

@cdcabrera  @jeff-phillips-18 @dtaylor113

**Comment by cdcabrera** [comment]
Unit tests eh, well they might have been helpful with the conversion as a base line comparison. But since they aren't there we could two part it @dtaylor113 @jeff-phillips-18 , and were there any limitations before?

I'm leaning more towards integrating them into this PR, at least a few basics to verify things are loading/showing up. It'll increase the length of time on the PR a bit, but it'll head towards the sweet spot of a well rounded/thought out piece.

**Comment by jeff-phillips-18** [comment]
@amarie401 I'm OK with adding unit tests as part of this PR or as a follow on.

**Comment by amarie401** [comment]
Sounds good! Thanks guys!

**Comment by dtaylor113** [comment]
> One question for @amarie401 @dtaylor113 @cdcabrera , is this a fix or a chore ?

I would think `chore` as underlying changes should be transparent to the end users.

**Comment by amarie401** [comment]
Hmmm...I would say that it's a chore since it's a conversion and all the major pieces are still working.

**Comment by jeff-phillips-18** [comment]
OK @amarie401, could you reword your commit please?

**Comment by dtaylor113** [comment]
Wow, really thought I had added the unit tests, as there are extensive ones [here](https://github.com/dtaylor113/manageiq-ui-self_service/blob/master/tests/blueprints/blueprint-canvas.directive.spec.js) and [here](https://github.com/dtaylor113/manageiq-ui-self_service/blob/master/tests/blueprints/blueprint-editor.directive.spec.js)
But I guess these existing 'blueprint canvas' unit tests would need to be updated to working with the generalized a-pf pfCanvas component.  This should be added as a new issue and can be addressed in a follow on PR.  -thanks

**Comment by cdcabrera** [comment]
I'm good with labeling this work as chore if we can work the unit tests in now... but my vote is for fix since it'll increment and allow consumers to pick their version

**Comment by dtaylor113** [comment]
I'm ok with `fix(..)` as it may possibly introduce a regression.

**Comment by amarie401** [comment]
In that case with the possibility of the rollback then I would agree on labeling it a fix

**Comment by jeff-phillips-18** [comment]
OK, I can go along with that.
