### PR TITLE
pfTableView Fixes

### LINKED ISSUE #440: pfTableView: error when items array is empty
On version 4.x, when the array of items provided to the pfTableView component is empty, the following error is thrown in the console:
```
Error: pfTableView - config.selectionMatchProp 'threadId' does not match any property in 'config.colummns'! Please set config.selectionMatchProp to one of these properties: threadId, threadState, threadName, waitedTime, blockedTime, inNative, suspended
    at angular.module.component.controller.ctrl.updateConfigOptions (angular-patternfly.js:11580)
    at angular.module.component.controller.ctrl.$onInit (angular-patternfly.js:11542)
    at angular.js:9509
    at forEach (angular.js:333)
    at nodeLinkFn (angular.js:9498)
    at angular.js:9886
    at processQueue (angular.js:16696)
    at angular.js:16712
    at Scope.$eval (angular.js:17994)
    at Scope.$digest (angular.js:17808)
```
The bug is in the following line of the validSelectionMatchProp() function:
```
var item = ctrl.items[0];
```

### LINKED ISSUE #441: pfTableView: error when items have more properties than the defined columns
On version 4.x, when the array of items provided to the pfTableView component contains objects with more properties than the defined columns, the following error is thrown in the console:
```
TypeError: Cannot set property '_DT_CellIndex' of undefined
    at _fnCreateTr (jquery.dataTables.js:3082)
    at _fnAddData (jquery.dataTables.js:2401)
    at HTMLTableRowElement.<anonymous> (jquery.dataTables.js:2429)
    at jquery.js:144
    at Function.map (jquery.js:467)
    at jQuery.fn.init.map (jquery.js:143)
    at _fnAddTr (jquery.dataTables.js:2427)
    at loadedInit (jquery.dataTables.js:1307)
    at HTMLTableElement.<anonymous> (jquery.dataTables.js:1332)
    at Function.each (jquery.js:374)
```

### LINKED ISSUE #449: pfTableView with toolbar - inconsistent with design
pfTableView with toolbar is inconsistent with PatternFly Data Tables design:
https://www.patternfly.org/pattern-library/widgets/#data-tables

Issues:
- "table-view-pf-toolbar" CSS class is missing in toolbar.
- The following CSS rules from `angular-datatables.css` are adding a top margin to the table:
```
table.dataTable,
table.dataTable.no-footer{
    margin: 1rem 0;
    width: 100% !important;
    border-top: 1px solid #DDDDDD;;
    border-bottom: 1px solid #DDDDDD;
}
```
- There is too much padding to the left of the toolbar action buttons.

screenshot1

### PR DESCRIPTION
**Pull request by dtaylor113**
Fixes #441 'pfTableView: error when items have more properties than the defined columns'
Fixes #440 'pfTableView: error when items array is empty'
Fixes #449 'pfTableView with toolbar - inconsistent with design'

image

**When no filter:**
image

### CODE REVIEW

File: src/toolbars/toolbar-component.js [hunk 1]
```diff
@@ -52,6 +52,7 @@ angular.module('patternfly.toolbars').component('pfToolbar', {
 
     function viewSelected (viewId) {
       ctrl.config.viewsConfig.currentView = viewId;
+      ctrl.config.isTableView = viewId === 'tableView';
```
Comment (jeff-phillips-18) [inline src/toolbars/toolbar-component.js]: Shouldn't this also be checked when first entering in the case where the original view is a tableView?

isTableView is not documented as an option in the config object.

Comment (dtaylor113) [inline src/toolbars/toolbar-component.js]: Removed 'isTableView' and are using the existing viewConfig.currentView.   Weird but in `setupConfig()` the `ctrl.config.viewsConfig.currentView` was being set to the view object; whereas elsewhere in the component, and in the unit tests, it is being set to an id.

Comment (jeff-phillips-18) [inline src/toolbars/toolbar-component.js]: What if the toolbar is associated with a view that is always a table view? There would be no viewConfig.

Comment (dtaylor113) [inline src/toolbars/toolbar-component.js]: In that case I used:
```
        viewsConfig: {
          currentView: 'tableView'
        }
```

Comment (dtaylor113) [inline src/toolbars/toolbar-component.js]: It's either we use the existing viewsConfig, or introduce a new config property like 'isTableView: true'

Comment (jeff-phillips-18) [inline src/toolbars/toolbar-component.js]: I would rather use the isTableView property on config but if a viewConfig is given, update that property based on the current view Id.

Comment (dtaylor113) [inline src/toolbars/toolbar-component.js]: Ok, fixed

File: src/toolbars/toolbar-component.js [hunk 2]
```diff
@@ -61,6 +62,11 @@ angular.module('patternfly.toolbars').component('pfToolbar', {
       return ctrl.config.viewsConfig && (ctrl.config.viewsConfig.currentView === viewId);
     }
 
+    function isTableViewSelected () {
+      return (ctrl.config.viewsConfig && (ctrl.config.viewsConfig.currentView === 'tableView')) ||
+             ctrl.config.isTableView;
```
Comment (jeff-phillips-18) [inline src/toolbars/toolbar-component.js]: A bit concerned that a mistake setting isTableView to true when also passing a viewConfig will cause this to return true even if a different view type is selected.

Comment (dtaylor113) [inline src/toolbars/toolbar-component.js]: Ok, fixed.   ng-doc also states:

> .isTableView - (Boolean) set to true if toolbar is only being used with a table view and viewsConfig is not defined.

File: src/toolbars/toolbar-component.js [hunk 3]
```diff
@@ -61,6 +62,11 @@ angular.module('patternfly.toolbars').component('pfToolbar', {
       return ctrl.config.viewsConfig && (ctrl.config.viewsConfig.currentView === viewId);
     }
 
+    function isTableViewSelected () {
+      return (ctrl.config.viewsConfig && (ctrl.config.viewsConfig.currentView === 'tableView')) ||
+             (!ctrl.config.viewsConfig && ctrl.config.isTableView);
+    }
+
```
Comment (jeff-phillips-18) [inline src/toolbars/toolbar-component.js]: More readable:

return ctrl.config.viewsConfig ? (ctrl.config.viewsConfig.currentView === 'tableView') : ctrl.config.isTableView);

Comment (dtaylor113) [inline src/toolbars/toolbar-component.js]: Agree, fixed
