### PR TITLE
fix(pfCard): Add loading state for pfCard

### LINKED ISSUE #658: The base dashboard card should have a loading state
The base dashboard card (http://www.patternfly.org/pattern-library/cards/base-card/#/design) should have a loading state similar to this:
screen shot 2017-10-23 at 9 52 33 am

We need to verify with Visuals which spinner should be used, as i think we want animation here.   @jennyhaines what are your thoughts?

### PR DESCRIPTION
**Pull request by amarie401**
## Description
Adding a loading state spinner to pfCard to fix #658 

[Rawgit](http://rawgit.com/amarie401/angular-patternfly/card-loading-state-dist/dist/docs/index.html#/api/patternfly.card.component:pfCard%20-%20Timeframe%20Filters)

## PR Checklist

- [X] Unit tests are included
- [X] Screenshots are attached (if there are visual changes in the UI)
- [X] A Designer (@beanh66) is assigned as a reviewer (if there are visual changes in the UI)

loadingstate

@beanh66 @jennyhaines @dtaylor113 @jeff-phillips-18 @serenamarie125

### CODE REVIEW

File: src/card/examples/card-timeframe.js [hunk 1]
```diff
@@ -40,6 +41,9 @@
        <pf-card head-title="Card Title" sub-title="Card Subtitle" show-top-border="true" filter="filterConfigHeader" style="width: 50%">
          Card Contents
        </pf-card>
+     <label class="label-title">Timeframe filter in header & loading state</label>
+       <pf-card show-spinner="true" head-title="Card Title" sub-title="Card Subtitle" show-top-border="true" filter="filterConfigHeader" style="width: 50%">
```
Comment (dtaylor113) [inline src/card/examples/card-timeframe.js]: Please tie this to a $scope var which is initially 'true'.  Then in a $timeout delay, have it set to 'false' .  Just so we can  see the state change.

**Comment by dtaylor113** [comment]
I'm wondering if we should also hide the filter dropdown (in header and/or footer) and the footer if the spinner is showing?  If the data isn't available yet, we probably shouldn't show a filter control yet.

**Comment by beanh66** [comment]
@dtaylor113 Agreed, I would think filters and actions should be hidden as well, thanks!

File: src/card/basic/card.component.js [hunk 2]
```diff
@@ -91,6 +92,7 @@ angular.module('patternfly.card').component('pfCard', {
     subTitle: '@?',
     showTopBorder: '@?',
     showTitlesSeparator: '@?',
+    showSpinner: '@?',
```
Comment (jeff-phillips-18) [inline src/card/basic/card.component.js]: Better to make this a binding and use true/false rather that 'true'/'false'

File: src/card/basic/card.component.js [hunk 3]
```diff
@@ -130,6 +130,9 @@ angular.module('patternfly.card').component('pfCard', {
 
     ctrl.$onInit = function () {
       ctrl.shouldShowTitlesSeparator = (!ctrl.showTitlesSeparator || ctrl.showTitlesSeparator === 'true');
+      if (angular.isUndefined(ctrl.showSpinner)) {
+        ctrl.showSpinner = 'false';
+      }
     };
```
Comment (jeff-phillips-18) [inline src/card/basic/card.component.js]: Once this is a binding you can use
`ctrl.showSpinner = ctrl.showSpinner === true`

File: src/card/basic/card.html [hunk 4]
```diff
@@ -3,10 +3,10 @@
     <div ng-if="$ctrl.showFilterInHeader()" ng-include="'card/basic/card-filter.html'"></div>
     <h2 class="card-pf-title">{{$ctrl.headTitle}}</h2>
   </div>
-
-  <span ng-if="$ctrl.subTitle" class="card-pf-subtitle">{{$ctrl.subTitle}}</span>
+  <span ng-class="{'hide': $ctrl.showSpinner === 'true'}" ng-if="$ctrl.subTitle" class="card-pf-subtitle">{{$ctrl.subTitle}}</span>
 
   <div class="card-pf-body">
+    <div ng-class="{'spinner spinner-lg': $ctrl.showSpinner === 'true'}"></div>
```
Comment (jeff-phillips-18) [inline src/card/basic/card.html]: This div should only exist if $ctrl.showSpinner

File: src/card/basic/card.html [hunk 5]
```diff
@@ -3,10 +3,10 @@
...
     <div ng-transclude></div>
```
Comment (jeff-phillips-18) [inline src/card/basic/card.html]: This should not be shown if showSpinner is true. You may need to use ng-show though due to the transclude.

File: src/card/basic/card.component.js (hunk 3 above)
Comment (amarie401) [reply src/card/basic/card.component.js]: ```shouldn't I do ctrl.showSpinner = ctrl.showSpinner === false``` since we want it to be false by default?

**Comment by amarie401** [comment]
@beanh66 should the top border be hidden as well? I updated the screenshot

File: src/card/examples/card-timeframe.js [hunk 6]
```diff
@@ -45,10 +46,19 @@
           footer="footerConfig" filter="filterConfig" style="width: 50%">
         Card Contents
      </pf-card>
+     <label class="label-title">Loading State</label>
+     <pf-card show-spinner="dataLoading" head-title="Card Title" sub-title="Card Subtitle" show-top-border="true" filter="filterConfigHeader" style="width: 50%">
```
Comment (dtaylor113) [inline src/card/examples/card-timeframe.js]: I'd add "Card Contents" here, between the <pf-card> and </pf-card>, just to show that transclusion will come through when the spinner is off.

Comment (amarie401) [reply src/card/examples/card-timeframe.js]: Will do!

File: src/card/basic/card.component.js (hunk 3 above)
Comment (jeff-phillips-18) [reply src/card/basic/card.component.js]: so you want it to be true if they pass false?

What I have above says it is true only if the specifically pass true. Any other value would resolve to false (the default).

File: src/card/basic/card.component.js [hunk 7]
```diff
@@ -130,6 +130,9 @@ angular.module('patternfly.card').component('pfCard', {
 
     ctrl.$onInit = function () {
       ctrl.shouldShowTitlesSeparator = (!ctrl.showTitlesSeparator || ctrl.showTitlesSeparator === 'true');
+      if (angular.isUndefined(ctrl.showSpinner)) {
```
Comment (jeff-phillips-18) [inline src/card/basic/card.component.js]: No need to check if it is defined.

File: src/card/basic/card.html [hunk 8]
```diff
@@ -1,15 +1,15 @@
 <div ng-class="$ctrl.showTopBorder === 'true' ? 'card-pf card-pf-accented' : 'card-pf'">
   <div ng-if="$ctrl.showHeader()" ng-class="$ctrl.shouldShowTitlesSeparator ? 'card-pf-heading' : 'card-pf-heading-no-bottom'">
-    <div ng-if="$ctrl.showFilterInHeader()" ng-include="'card/basic/card-filter.html'"></div>
+    <div ng-class="{'hide': $ctrl.showSpinner === true}" ng-if="$ctrl.showFilterInHeader()" ng-include="'card/basic/card-filter.html'"></div>
```
Comment (dtaylor113) [inline src/card/basic/card.html]: This might be better written as:
`<div ng-if="$ctrl.showFilterInHeader() && !$ctrl.showSpinner" ...`
...or you could even move the logic into the $ctrl.showFilterInHeader() function.

File: src/card/basic/card.component.js (hunk 7 above)
Comment (amarie401) [reply src/card/basic/card.component.js]: Okay no prob!

File: src/card/basic/card.html [hunk 9]
```diff
@@ -1,15 +1,15 @@
...
     <h2 class="card-pf-title">{{$ctrl.headTitle}}</h2>
   </div>
-
-  <span ng-if="$ctrl.subTitle" class="card-pf-subtitle">{{$ctrl.subTitle}}</span>
+  <span ng-class="{'hide': $ctrl.showSpinner === true}" ng-if="$ctrl.subTitle" class="card-pf-subtitle">{{$ctrl.subTitle}}</span>
 
   <div class="card-pf-body">
+    <div ng-show="$ctrl.showSpinner" ng-class="{'spinner spinner-lg': $ctrl.showSpinner}"></div>
```
Comment (jeff-phillips-18) [inline src/card/basic/card.html]: This should be ng-if and no need to ng-class since it won't be shown without the class.

File: src/card/basic/card.html [hunk 10]
```diff
@@ -1,15 +1,15 @@
 <div ng-class="$ctrl.showTopBorder === 'true' ? 'card-pf card-pf-accented' : 'card-pf'">
   <div ng-if="$ctrl.showHeader()" ng-class="$ctrl.shouldShowTitlesSeparator ? 'card-pf-heading' : 'card-pf-heading-no-bottom'">
-    <div ng-if="$ctrl.showFilterInHeader()" ng-include="'card/basic/card-filter.html'"></div>
+    <div ng-class="{'hide': $ctrl.showSpinner === true}" ng-if="$ctrl.showFilterInHeader()" ng-include="'card/basic/card-filter.html'"></div>
     <h2 class="card-pf-title">{{$ctrl.headTitle}}</h2>
   </div>
-
-  <span ng-if="$ctrl.subTitle" class="card-pf-subtitle">{{$ctrl.subTitle}}</span>
+  <span ng-class="{'hide': $ctrl.showSpinner === true}" ng-if="$ctrl.subTitle" class="card-pf-subtitle">{{$ctrl.subTitle}}</span>
```
Comment (dtaylor113) [inline src/card/basic/card.html]: I think the standard we use is ng-if instead of ng-class/hide, see comment above.

File: src/card/basic/card.html [hunk 11]
```diff
@@ -1,15 +1,15 @@
...
 
   <div class="card-pf-body">
+    <div ng-show="$ctrl.showSpinner" ng-class="{'spinner spinner-lg': $ctrl.showSpinner}"></div>
     <div ng-transclude></div>
```
Comment (jeff-phillips-18) [inline src/card/basic/card.html]: This should be ng-show="!$ctrl.showSpinner"

File: src/card/basic/card.html [hunk 12]
```diff
@@ -1,15 +1,15 @@
...
   </div>
-  <div ng-if="$ctrl.footer" class="card-pf-footer">
+  <div ng-class="{'hide': $ctrl.showSpinner === true}" ng-if="$ctrl.footer" class="card-pf-footer">
```
Comment (dtaylor113) [inline src/card/basic/card.html]: I think the standard we use is ng-if instead of ng-class/hide, see comment above.

Comment (jeff-phillips-18) [inline src/card/basic/card.html]: I'd rather use ng-show than adding the 'hide' class

File: src/card/basic/card.html (hunk 8 above)
Comment (jeff-phillips-18) [inline src/card/basic/card.html]: ng-show rather than adding the 'hide' class?

File: src/card/basic/card.html (hunk 12 above)
Comment (dtaylor113) [reply src/card/basic/card.html]: :+1:

File: test/card/basic/card.spec.js [hunk 13]
```diff
@@ -85,6 +85,19 @@ describe('Component: pfCard', function() {
...
+      element = compileCard('<pf-card head-title="My card title" sub-title="My card subtitle title" show-top-border="false">Inner content goes here</pf-card>', $scope);
+      cardClass = angular.element(element).find('.spinner-lg');
+      expect(cardClass.length).toBe(0);
+
+      // setting to true should show spinner
+      element = compileCard('<pf-card head-title="My card title" show-spinner="true" sub-title="My card subtitle title" show-top-border="false">Inner content goes here</pf-card>', $scope);
+      cardClass = angular.element(element).find('.spinner-lg');
+      expect(cardClass.length).toBe(1);
+    });
+
```
Comment (jeff-phillips-18) [inline test/card/basic/card.spec.js]: Might be better to test the binding. Use show-spinner="dataLoading" then change the value and test again.

Comment (amarie401) [reply test/card/basic/card.spec.js]: Sounds good. I'll go back to this

**Comment by amarie401** [comment]
After changing the ```ng-class``` to ```ng-if``` I noticed there is a bit of lag and the icon is still there even after the data loads. I tried changing it to ```ng-show``` instead and there still seems to be a bit of lag that wasn't present before. I'm not sure if it has to do with the ```ng-class``` allowing it still be apart of the DOM but just hiding it which would maybe allow for faster load time but I would think ng-show would also do the same? @jeff-phillips-18 @dtaylor113 

loading-state-2

File: src/card/basic/card.html (hunk 8 above)
Comment (amarie401) [reply src/card/basic/card.html]: Seems to be causing a lag with ng-if and ng-show

**Comment by serenamarie125** [comment]
Although I know in the issue uor guidance was to not have associated "Loading" text, I'm rethinking that decision.  

Reasoning is that we have a similar question that just came in about a content view loading state - and in that situation, i think we need "Loading".  Thoughts on adding it here for consistency with what we should do in a view as well as consistency with No Data Available state having an icon/label pair as well @beanh66 @jeff-phillips-18 @jennyhaines ?

File: src/card/basic/card.html (hunk 8 above)
Comment (dtaylor113) [reply src/card/basic/card.html]: Should be one or the other.   I did have to change ng-ifs to ng-shows in order to not break OpenShift e2e/Protractor tests, so I'd go with ng-show.

**Comment by beanh66** [comment]
@serenamarie125 that is fine with me. I was initially debating the label because I felt like it would be more consistent with the empty states we have. I can see where it is really necessary on larger views or cards. @jennyhaines would you be okay with that or would you rather see it optional maybe?

**Comment by jeff-phillips-18** [comment]
@serenamarie125 @beanh66 I think we should allow passing a dataLoadingText value that can be shown along with the spinner if desired by the application.

**Comment by amarie401** [comment]
I agree with having a dataLoadingText value

**Comment by dtaylor113** [comment]
> After changing the ng-class to ng-if I noticed there is a bit of lag now and the icon is still there for a few seconds even after the data loads.

I think I've run into this before, and I think it was a spinner as well.   I believe I did have to replace `ng-if` and `ng-show` with `ng-class`.  Not saying this was right, but it did fix the problem.

It might have something to do with the angular lifecycle, may need to throw in a `$scope.$digest()` in the controller somewhere.  Looking into it....

**Comment by beanh66** [comment]
@jeff-phillips-18 agreed, so are you saying it would be optional?

File: src/card/basic/card.component.js [hunk 14]
```diff
@@ -44,37 +45,44 @@
...
-         'used': '450',
-         'total': '500'
-       };
+         $scope.units5 = 'I/Ops';
+
+       $timeout(function () {
+         $scope.dataLoading = false;
+
+         $scope.data2 = {
+           'used': '25',
```
Comment (dtaylor113) [inline src/card/basic/card.component.js]: You don't need any of these dataN objects

File: src/charts/utilization-bar/utilization-bar-chart.component.js [hunk 15]
```diff
@@ -172,8 +172,16 @@ angular.module('patternfly.charts').component('pfUtilizationBarChart', {
       prevChartData = angular.copy(ctrl.chartData);
       prevLayout = angular.copy(ctrl.layout);
 
+      if (!ctrl.chartData) {
```
Comment (dtaylor113) [inline src/charts/utilization-bar/utilization-bar-chart.component.js]: Why are there changes in `utilization-bar-chart.component.js`?  Is this a git/rebase/commit issue?

File: src/card/basic/card.component.js [hunk 16]
```diff
@@ -44,37 +45,44 @@
...
-       $scope.data5 = {
-         'used': '450',
-         'total': '500'
-       };
+         $scope.units5 = 'I/Ops';
+
+       $timeout(function () {
+         $scope.dataLoading = false;
+
+         $scope.data2 = {
```
Comment (dtaylor113) [inline src/card/basic/card.component.js]: Not sure you need the $scope.dataN objects in the $timeout.

**Comment by dtaylor113** [comment]
LGTM, believe we are just waiting on the `dataLoadingText` stuff

File: src/card/basic/card.component.js (hunk 16 above)
Comment (amarie401) [reply src/card/basic/card.component.js]: @jeff-phillips-18 would it be fine to remove the data objects?

Comment (jeff-phillips-18) [reply src/card/basic/card.component.js]: Yes, trying to mimic what an application would do. If the data is loading, then there is no data until it is loaded. This uncovered an issue were we expect the data to always be set.

**Comment by jeff-phillips-18** [comment]
@beanh66 Yes, I think it should be optional. Text can be specified by the application or left out.

File: src/card/basic/card.component.js (hunk 16 above)
Comment (dtaylor113) [reply src/card/basic/card.component.js]: ok, thanks

File: src/card/basic/card.html [hunk 17]
```diff
@@ -1,15 +1,16 @@
...
+  <span ng-if="$ctrl.subTitle && !$ctrl.showSpinner" class="card-pf-subtitle">{{$ctrl.subTitle}}</span>
 
-  <span ng-if="$ctrl.subTitle" class="card-pf-subtitle">{{$ctrl.subTitle}}</span>
-
-  <div class="card-pf-body">
-    <div ng-transclude></div>
+  <div class="card-pf-body" ng-class="{'show-spinner': $ctrl.showSpinner}">
+    <label ng-if="!$ctrl.spinnerText" class="sr-only">Loading</label>
+    <div ng-if="$ctrl.showSpinner" class="spinner spinner-lg" aria-hidden="true"></div>
+    <div ng-class="{'hide-body': $ctrl.showSpinner}" ng-transclude></div>
```
Comment (jeff-phillips-18) [inline src/card/basic/card.html]: Shouldn't we be displaying $ctrl.spinnerText if it is set?

Comment (amarie401) [reply src/card/basic/card.html]: Working on that now :)

Comment (amarie401) [reply src/card/basic/card.html]: whoops did that backwards. Fixing.. :)

**Comment by dtaylor113** [comment]
Should the "Loading" spinnerText be centered under the spinner?
image

File: test/card/basic/card.spec.js [hunk 18]
```diff
@@ -85,6 +85,21 @@ describe('Component: pfCard', function() {
...
+      cardClass = angular.element(element).find('.spinner-lg');
+      expect(cardClass.length).toBe(0);
+
+      // When data is loading, spinner should be present
+      $scope.dataLoading = true;
+      element = compileCard('<pf-card head-title="My card title" show-spinner="dataLoading" sub-title="My card subtitle title" show-top-border="false">Inner content goes here</pf-card>', $scope);
+      cardClass = angular.element(element).find('.spinner-lg');
+      expect(cardClass.length).toBe(1);
+    });
+
```
Comment (dtaylor113) [inline test/card/basic/card.spec.js]: Pls add unit test for spinnerText, thanks

Comment (amarie401) [reply test/card/basic/card.spec.js]: Okay will do!

**Comment by jeff-phillips-18** [comment]
I believe this should be a feat rather than a fix.

**Comment by amarie401** [comment]
No problem, will change to a feat.

**Comment by jeff-phillips-18** [comment]
@dtaylor113 The text should be to the right of the spinner. There are instances where the body content may not present enough vertical space to show the spinner and text stacked.

**Comment by beanh66** [comment]
@jeff-phillips-18 I was thinking it would be centered under the icon, similar to the empty state. Could we do that when there is enough space and when there is not, maybe just hide the text? 

@serenamarie125 Thoughts?

**Comment by jeff-phillips-18** [comment]
@beanh66 not sure we can tell if it will fit or not. I can't think of any way anyways.

**Comment by jeff-phillips-18** [comment]
This is what we have now:
image

**Comment by beanh66** [comment]
@jeff-phillips-18 Oh okay, got it. Well it looks a lot better being centered, I just didn't like the large separation between the icon/text originally :)

**Comment by jeff-phillips-18** [comment]
The ... is just example text. Applications can do what they will.

**Comment by amarie401** [comment]
I have no issue with the "..." since it is just example text and anything can be entered in by the user to suit their needs

**Comment by amarie401** [comment]
@beanh66 I have removed the "..."

**Comment by amarie401** [comment]
@beanh66 I have removed the "..." from the example text and changed it to "Loading" to be more consistent

**Comment by beanh66** [comment]
Thanks, sorry for nit picking! 😆
