### PR TITLE
Fix notification drawer accordion panel sizing

### LINKED ISSUE #545: Notification drawer accordion does not work consistently
Was talking with @jeff-phillips-18 about some issues, he noted height calculation.  

I've been experiencing issues where items are truncated.  For example, I have 15 items in this list, but only 7 are visible & it will not scroll consistently:

screen shot 2017-08-03 at 12 21 19 am

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
## Description
Update sizes when elements in the notification drawer are updated.
Update collapse children to not have a intermediate parent.
Fix for example notification drawer body html indentation error.

Fixes #545 

@benjaminapetersen

### CODE REVIEW

File: src/utils/fixed-accordion.directive.js [hunk 1]
```diff
@@ -78,24 +85,21 @@ angular.module('patternfly.utils').directive('pfFixedAccordion', function ($wind
 
           if (angular.isDefined($scope.scrollSelector)) {
             scroller = angular.element(collapsePanel[0].querySelector($scope.scrollSelector));
-            if (scroller.length === 1) {
+            if (scroller.length > 0) {
               scrollElement = angular.element(scroller[0]);
```
Comment (dtaylor113) [inline src/utils/fixed-accordion.directive.js]: Nit. could remove "> 0"

Comment (jeff-phillips-18) [inline src/utils/fixed-accordion.directive.js]: fixed

File: src/notification/notification-drawer.component.js [hunk 2]
```diff
@@ -51,6 +51,12 @@ angular.module('patternfly.notification').component('pfNotificationDrawer', {
       });
     };
 
+    var updateAccordionSizing = function () {
+      $timeout(function () {
```
Comment (benjaminapetersen) [inline src/notification/notification-drawer.component.js]: Any concerns about performance here?  if `$onChanges` is triggered frequently, do you want to be triggering resize often, or would a `debounce`/`throttle` be in order?  I'm also curious about `100`, vs (`0` or any other small #) if its arbitrary or standardized across patternfly angular for this kind of thing.

File: src/notification/notification-drawer.html [hunk 3]
```diff
@@ -19,16 +19,15 @@ <h4 class="panel-title">
           <span class="panel-counter" ng-include src="$ctrl.subheadingInclude"></span>
         </div>
         <div class="panel-collapse collapse" ng-class="{in: notificationGroup.open || $ctrl.notificationGroups.length === 1}">
```
Comment (cdcabrera) [inline src/notification/notification-drawer.html]: Nit: truthy check instead...

Comment (jeff-phillips-18) [inline src/notification/notification-drawer.html]: huh?

File: src/notification/notification-drawer.component.js (hunk 2 above)
Comment (jeff-phillips-18) [inline src/notification/notification-drawer.component.js]: I don't believe onChanges will get call that frequently. Typically most of these won't change, but should they, the size needs to be recalculated. Also, its only done if the draw is shown and one of these values change.

We've typically used 100 just to get past any follow up changes and get thru a digest cycle or two. Main idea is to get past the current digest cycle anyhow.

File: src/notification/notification-drawer.html (hunk 3 above)
Comment (jeff-phillips-18) [inline src/notification/notification-drawer.html]: But it must be exactly 1.

Comment (benjaminapetersen) [inline src/notification/notification-drawer.html]: Right, this is the single panel option. Sorry, just saw the truthy "huh" :)

**Comment by benjaminapetersen** [comment]
@jeff-phillips-18 I've built this & pulled it into the console to test.  Works much better, big improvement, thx!
