### PR TITLE
fix(pfFilter): do not allow empty filters

### LINKED ISSUE #509: pfFilter: Should not allow empty filters
If I hit the [Enter] key with no filter criteria specified in the filter input textbox, the pfFilter component adds an 'empty' applied filter.  This should be prevented.

### PR DESCRIPTION
**Pull request by dtaylor113**
## Description
Updated so that hitting [Enter] on an empty input filter field doesn't create an empty filter.

Fixes #509

### CODE REVIEW

File: src/filters/simple-filter/filter-fields-component.js [hunk 1]
```diff
@@ -89,7 +89,7 @@ angular.module('patternfly.filters').component('pfFilterFields', {
     }
 
     function onValueKeyPress (keyEvent) {
-      if (keyEvent.which === 13) {
+      if (keyEvent.which === 13 && ctrl.currentValue && ctrl.currentValue.length > 0) {
```
Comment (jeff-phillips-18) [inline src/filters/simple-filter/filter-fields-component.js]: Simplify to:
` if (keyEvent.which === 13 && ctrl.currentValue.length) {`

Comment (dtaylor113) [inline src/filters/simple-filter/filter-fields-component.js]: ```ctrl.currentValue``` is null
