### PR TITLE
Notification Drawer Updates

### LINKED ISSUE #414: Notification drawer TypeError if notification-groups is undefined
Typically directives fail silently rather than throwing an error like this:

screen shot 2017-02-14 at 10 01 28 am

5546 `scope.notificationGroups.forEach` should prob check if there is an array before looping.  If throwing an error is preferred, a more descriptive error message would be helpful.

### LINKED ISSUE #419: Passing variables to patterfly-notification-drawer triggers infinite loop
If I pass the template includes via `$scope` variables like this:

```JavaScript
          angular.extend($scope, {
            notificationGroups: [{
              heading: 'Tab 1',
              subHeading: 'woohoo!',
              notifications: [{
                unread: true,
                message: 'Hello world'
              }]
            }],
            headingInclude: 'views/directives/notifications/heading.html',
            subheadingInclude: 'views/directives/notifications/subheading.html',
            notificationBodyInclude: 'views/directives/notifications/notification-body.html',
            notificationFooterInclude: 'views/directives/notifications/notification-footer.html',
            customScope: {}
          });
```

```html
  <div
    pf-notification-drawer
    heading-include="headingInclude"
    subheading-include="subheadingInclude"
    notification-body-include="notificationBodyInclude"
    notification-footer-include="notificationFooterInclude"
    custom-scope="customScope">
  </div>
```

My console logs some pretty gnarly things:

screen shot 2017-02-16 at 5 00 39 pm

And the `chrome-helper` process associated with this page very quickly consumes over `1GB` of memory (this is when I force quite, it seems to climb indefinitely).

### LINKED ISSUE #420: Its not clear in the docs that the class navbar-pf-vertical is required for pf-notification-drawer to have height
Without `<div class="navbar-pf-vertical">` wrapper, a `<pf-notification-drawer>` will have no height.  Its not clear that this is essential (or why it would be).  The example code does show the class being used, but it appears to be boilerplate along with some other classes.

### LINKED ISSUE #421: The pf-notification-drawer could use a built-in dismiss action
Using the "bell" in the top nav makes sense for opening a notification drawer, but seems a bit odd to also use as the closing action.  I'm curious if a "dismiss" action could be added at the top near the `<<` icon, or provide a `footer-include` attribute (not `notification-footer`, but one for the drawer itself) that would allow for a location to place a button to hook up a "dismiss" to toggle the `hideDrawer` attrib.  

screen shot 2017-02-16 at 10 31 42 pm
screen shot 2017-02-16 at 10 31 50 pm

### LINKED ISSUE #429: pf-notification-drawer cannot take an object for notificationGroups
Its pretty common to be able to pass an array or an object as an arg, but the `pf-notification-drawer` will only accept an array:

```JavaScript
scope.$watch('notificationGroups', function () {
 var openFound = false;
 // this line demands that notificationGroups be an array :(
 scope.notificationGroups.forEach(function (group) {
   if (group.open) {
     if (openFound) {
       group.open = false;
     } else {
       openFound = true;
     }
   }
 });
});
```
Using a utility like `angular.forEach` would provide some helpful flexibility & eliminate the need for glue code to swap objects and arrays back and forth.

### LINKED ISSUE #430: notification instances with long text break layout in pf-notification-drawer
The css for the message in the vertical accordion is set to `display:inline-block`, which breaks down if you have messages larger than a very simple, short sentence. Example:

screen shot 2017-03-08 at 10 10 05 am

Originally noticed when passing the following text in the OpenShift Web Console: `Created new replication controller "mongodb-1" for version 1`.

### LINKED ISSUE #431: The pf-notification-drawer doesn't have a built-in way to use a "no notifications" message
Ideally there would be a default message if there are no notifications: 
screen shot 2017-03-08 at 10 56 17 am

### PR DESCRIPTION
**Pull request by jeff-phillips-18**
Updates to latest Patternfly design pattern from: https://github.com/patternfly/patternfly-design/pull/297
Bumps https://github.com/patternfly/patternfly version to 3.26.0  

Fixes #414
Fixes #419 
Fixes #420 - Adds documentation on styling for drawer with different navigation layouts
Fixes #421 - Adds a close button to the notification drawer title area
Fixes #430 - Update layout to handle long notification messages
Fixes #429 #432 - Allows a single group to be used thus not using an accordion for groups
Fixes #431 - Displays the pf-empty-state when there are no notifications or none in a particular group. Allows setting the empty message for each.

@benjaminapetersen

### CODE REVIEW

**Comment by benjaminapetersen** [comment]
Great, taking a look!

**Comment by benjaminapetersen** [comment]
Running `grunt serve` & noticed the `x` on the docs file has a shadow: 
screen shot 2017-07-26 at 9 45 59 am

**Comment by benjaminapetersen** [comment]
I also have a scrollable 'empty message' under one of the headings:

screen shot 2017-07-26 at 9 48 07 am

**Comment by jeff-phillips-18** [comment]
@benjaminapetersen Did you update the patternfly version?

**Comment by benjaminapetersen** [comment]
I did a `bower install` before `grunt serve`, which gave me:
```
$ bower install
bower patternfly#>=3.26.0   not-cached https://github.com/patternfly/patternfly.git#>=3.26.0
bower patternfly#>=3.26.0      resolve https://github.com/patternfly/patternfly.git#>=3.26.0
bower bootstrap-switch#<=3.3.3  cached https://github.com/nostalgiaz/bootstrap-switch.git#3.3.3
bower bootstrap-switch#<=3.3.3         validate 3.3.3 against https://github.com/nostalgiaz/bootstrap-switch.git#<=3.3.3
bower patternfly#>=3.26.0              checkout v3.26.0
bower patternfly#>=3.26.0          invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .css files: ["dist/css/patternfly.css","dist/css/patternfly-additions.css"]
bower patternfly#>=3.26.0              resolved https://github.com/patternfly/patternfly.git#3.26.0
bower bootstrap-switch#<=3.3.3          install bootstrap-switch#3.3.3
bower patternfly#>=3.26.0               install patternfly#3.26.0
```

**Comment by benjaminapetersen** [comment]
The empty message definitely helps.  Curious if we would want a want to have a single "No notifications" message if all of the tabs are empty.  It may annoy a user to open each tab & get the same message over and over:

screen shot 2017-07-26 at 10 08 16 am

That may be able to be solved programmatically by updating the `notifications-body.html` with something like:

```html
<div ng-if="!totalNotificationCount">
   <!-- show a message if there zero notifications -->
</div>
<div ng-if="totalNotificationCount">
   <!-- show the current body -->
</div>
```
Another possibility might be to provide a new attrib for empty state:

```html
notification-body-include="notification-body.html"
notification-body-empty-include="notification-body-empty.html"
```

**Comment by jeff-phillips-18** [comment]
@benjaminapetersen I'd like to leave the 'all groups are empty' issue for further thought and not attempt to address in this PR. I'd like to hear some UX perspectives first.

**Comment by benjaminapetersen** [comment]
Works for me, I can probably just do the first option in the web console for now.

**Comment by jeff-phillips-18** [comment]
Feel free to add an issue if you'd like.

**Comment by benjaminapetersen** [comment]
Ok will do

File: src/notification/examples/notification-drawer.js [hunk 1]
```diff
@@ -0,0 +1,457 @@
...
+         $scope.actionsText = newText + "\n" + $scope.actionsText;
+       };
+
+       $scope.customScope.markRead = function (notification) {
+         if (notification.unread) {
+           notification.unread = false;
+           $scope.actionsText = "Mark notification read" + "\n" + $scope.actionsText;
+           var notificationGroup = $scope.groups.find(function(group) {
+             return group.notifications.find(function(nextNotification) {
+               return notification == nextNotification;
```
Comment (jeff-phillips-18) [inline src/notification/examples/notification-drawer.js]: Fixed. Thanks.
